.travis.yml, Dockerfile, docker-compose.yml, scripts/run-docker-tests.sh
Attend to recommendations in https://giorgos.sealabs.net/build-and-test-against-docker-images-in-travis.html
I want to see de docker-compose version https://github.com/docker/compose/issues/2172
Remove links https://docs.docker.com/compose/compose-file/#links
Remove cached image option...
=> Try to debug direction of postgres

.travis.yml
Validate with travis lint .travis.yml
=> update secrets, remove stages

.travis.yml, Dockerfile
hotfix makefile installing dependencies pyrcc5 and lrelease
=> hotfix makefile installing dependencies pyrcc5 and lrelease

.travis.yml
Like this:
- asistente_ladm_col.zip
- asistente_ladm_col/
- config/
- gui/ 
- ...
=> Zipped folder name should be in lowercase

Dockerfile
Releated with
https://github.com/AgenciaImplementacion/projectgenerator/issues/3
=> Update psycopg2 to a newer version

asistente_ladm_col/gui/point_spa_uni_cadastre_wizard.py, asistente_ladm_col/tests/test_copy_csv_points_to_db.py, asistente_ladm_col/ui/wiz_add_points_cadastre.ui, asistente_ladm_col/utils/qgis_utils.py
=> Add fixed separators with combobox values, and others separators in tab

asistente_ladm_col/tests/resources/.gitignore, asistente_ladm_col/tests/test_quality_validations.py, asistente_ladm_col/tests/test_topology.py, asistente_ladm_col/tests/utils.py
Copy file using _ (underscore) prefix for name
=> [tests] Copy file instead of using original

asistente_ladm_col/asistente_ladm_col_plugin.py, asistente_ladm_col/gui/controlled_measurement_dialog.py, asistente_ladm_col/processing/models/model_group_points.model3, asistente_ladm_col/ui/controlled_measurement_dialog.ui
Add processing model to group points and create a new point layer with average points.
It still lacks ways to filter out some points, for instance, those that are not well defined.
=> [gui] Controlled measurement prototype

asistente_ladm_col/config/general_config.py, asistente_ladm_col/lib/dbconnector/pg_connector.py
Add of validations for functionality connect of plugin, respect to exsistence of schema and valid model LADM.
=> Add validation for schema and LADM model

asistente_ladm_col/config/general_config.py, asistente_ladm_col/config/symbology.py, asistente_ladm_col/config/table_mapping_config.py, asistente_ladm_col/resources/styles/style_boundary.qml, asistente_ladm_col/resources/styles/style_boundary_point.qml, asistente_ladm_col/resources/styles/style_building_25.qml, asistente_ladm_col/resources/styles/style_building_point.qml, asistente_ladm_col/resources/styles/style_building_unit_25.qml, asistente_ladm_col/resources/styles/style_building_unit_point.qml, asistente_ladm_col/resources/styles/style_line_error.qml, asistente_ladm_col/resources/styles/style_plot_point.qml, asistente_ladm_col/resources/styles/style_plot_polygon.qml, asistente_ladm_col/resources/styles/style_point_error.qml, asistente_ladm_col/resources/styles/style_polygon_error.qml, asistente_ladm_col/resources/styles/style_survey_point.qml, asistente_ladm_col/utils/qgis_utils.py, asistente_ladm_col/utils/quality.py, asistente_ladm_col/utils/symbology.py
=> [styles] Set styles from QML files

asistente_ladm_col/config/general_config.py, asistente_ladm_col/gui/settings_dialog.py, asistente_ladm_col/lib/source_handler.py, asistente_ladm_col/utils/qgis_utils.py
Cases like no Internet connection, server unreachable, not valid service, and the like; show feedback.
=> [sources] Handle edge cases when uploading

asistente_ladm_col/processing/algs/InsertFeaturesToLayer.py, asistente_ladm_col/utils/qgis_utils.py
Also, improve feedback to users.
=> [processing] Improve refactor fields

asistente_ladm_col/asistente_ladm_col_plugin.py, asistente_ladm_col/gui/dlg_topological_edition.py, asistente_ladm_col/gui/toolbar.py, asistente_ladm_col/ui/dlg_topological_edition.ui, asistente_ladm_col/utils/qgis_utils.py
That is, move a node in all 3 layers at once.
=> [topology] Enable topological edition in Plot, Boundary and Boundary Point

asistente_ladm_col/asistente_ladm_col_plugin.py, asistente_ladm_col/config/table_mapping_config.py, asistente_ladm_col/utils/qgis_utils.py
+ [x] Replace +\' \'+ by ||
+ Col_Party:
+ [ ] Calculate field `nombre` automatically. _No se pudo, parece haber bug de QGIS aquí._
+ [x] Adjust display expression to reflect also legal parties.
+ Group party:
+ [x] Evaluate display expression when adding parties to the GUI left list.
=> Adjust display expressions

asistente_ladm_col/gui/settings_dialog.py, asistente_ladm_col/i18n/Asistente-LADM_COL_es.ts, asistente_ladm_col/ui/settings_dialog.ui
Inside this branch we be able to find the add to get data from Project Generator.
=> Add function to import connection settings from Project Generator

asistente_ladm_col/utils/geometry.py
Simple adjustment to handle the persistence of layer.getFeatures in memory
=> simple adjustments: persistence in memory layer.getFeatures

asistente_ladm_col/gui/create_boundaries_cadastre_wizard.py
This is the solution for this issue [96](https://github.com/AgenciaImplementacion/Asistente-LADM_COL/issues/96#event-1901819117)
Fix #96
=> solution for the configuration of snapping with boundary point in the creation of boundaries

asistente_ladm_col/config/general_config.py, asistente_ladm_col/i18n/Asistente-LADM_COL_es.ts, asistente_ladm_col/tests/test_quality_validations.py, asistente_ladm_col/utils/geometry.py
Handle the error generated by running the algorithm polygonstolines
=> Handle the error generated by running the algorithm polygonstolines

asistente_ladm_col/asistente_ladm_col_plugin.py, asistente_ladm_col/config/general_config.py, asistente_ladm_col/gui/reports.py, asistente_ladm_col/lib/dbconnector/pg_connector.py, asistente_ladm_col/utils/qgis_utils.py, asistente_ladm_col/utils/qt_utils.py
Several improvements to Annex 17:
+ Handle JAVA_HOME
+ Make sure encoding is always set (taken from Project Generator)
+ Handle version for dependencies (now in GitHub)
+ Use DB layers for overlay instead of WMSs
=> Reports: use db instead of wms

asistente_ladm_col/gui/create_points_cadastre_wizard.py, asistente_ladm_col/utils/qgis_utils.py
It add functionality in background for detect decimal point for latitude and longitude coordinates, and pass this value like parameter to function responsible for make layer to import csv points.
Fix #145
=> Adding function to detect decimal point in csv import

asistente_ladm_col/gui/create_points_cadastre_wizard.py, asistente_ladm_col/gui/reports.py, asistente_ladm_col/utils/qgis_utils.py, asistente_ladm_col/utils/qt_utils.py
=> Add new function for clean url for any OS and improve open file browser

asistente_ladm_col/gui/qgis_model_baker/dlg_export_data.py, asistente_ladm_col/gui/qgis_model_baker/dlg_import_data.py, asistente_ladm_col/gui/qgis_model_baker/dlg_import_schema.py, asistente_ladm_col/lib/dbconnector/db_connector.py, asistente_ladm_col/lib/dbconnector/gpkg_connector.py
merge changes for qgis model baker integration
=> [fix] merge changes for qgis model baker integration

asistente_ladm_col/utils/qgis_utils.py
Simple adjustment to get layers
=> [fix] adjustment to get layers

asistente_ladm_col/config/general_config.py, asistente_ladm_col/gui/create_building_cadastre_wizard.py, asistente_ladm_col/gui/create_building_unit_cadastre_wizard.py, asistente_ladm_col/gui/create_geoeconomic_zone_valuation_wizard.py, asistente_ladm_col/gui/create_physical_zone_valuation_wizard.py, asistente_ladm_col/gui/create_points_cadastre_wizard.py, asistente_ladm_col/gui/create_right_of_way_cadastre_wizard.py, asistente_ladm_col/gui/dialog_import_from_excel.py, asistente_ladm_col/gui/log_quality_dialog.py, asistente_ladm_col/gui/qgis_model_baker/dlg_export_data.py, asistente_ladm_col/gui/qgis_model_baker/dlg_import_schema.py, asistente_ladm_col/lib/dbconnector/pg_connector.py, asistente_ladm_col/utils/logic_checks.py, asistente_ladm_col/utils/qt_utils.py, asistente_ladm_col/utils/quality.py
Replace single quotes by double quotes in translate strings
=> [fix] Replace single quotes by double quotes in translate strings

asistente_ladm_col/gui/settings_dialog.py, asistente_ladm_col/lib/dbconnector/db_connector.py, asistente_ladm_col/lib/dbconnector/pg_connector.py
* Fix connection to remote DBs.
* Use postgres as default database
* Handle "the user doesn't have permissions over the schema"
=> [core] control except schema privileges

asistente_ladm_col/config/general_config.py, asistente_ladm_col/gui/dlg_get_java_path.py, asistente_ladm_col/gui/qgis_model_baker/dlg_export_data.py, asistente_ladm_col/gui/qgis_model_baker/dlg_import_data.py, asistente_ladm_col/gui/qgis_model_baker/dlg_import_schema.py, asistente_ladm_col/gui/reports.py, asistente_ladm_col/ui/dlg_get_java_path.ui, asistente_ladm_col/utils/qgis_model_baker_utils.py
Add custom dialog to set java path. 
Test for:
Fix #198
=> [core] Add java home dialog. Set JavaPath setting

asistente_ladm_col/gui/dialog_quality.py, asistente_ladm_col/i18n/Asistente-LADM_COL.pro, asistente_ladm_col/i18n/Asistente-LADM_COL_es.ts
- Update translations
- Remove empty group error layer
- We erase the group error layer every time it runs quality rules
=> Bugs logic consistency rules

asistente_ladm_col/utils/qgis_utils.py
Remove warning associate to unclosed socket
=> Remove ResourceWarning associated to unclosed socket

asistente_ladm_col/config/table_mapping_config.py, asistente_ladm_col/gui/associate_extaddress_cadastre_wizard.py
Fix https://github.com/AgenciaImplementacion/Asistente-LADM_COL/issues/206
=> Creates an OID record after creating an extaddress [fix issue_206]

asistente_ladm_col/gui/qgis_model_baker/dlg_export_data.py, asistente_ladm_col/gui/qgis_model_baker/dlg_import_data.py, asistente_ladm_col/gui/qgis_model_baker/dlg_import_schema.py
=> Resize qdialog and display log when error occurs

asistente_ladm_col/config/help_strings.py, asistente_ladm_col/gui/create_parcel_cadastre_wizard.py, asistente_ladm_col/gui/create_responsibility_cadastre_wizard.py, asistente_ladm_col/gui/create_restriction_cadastre_wizard.py, asistente_ladm_col/gui/create_right_cadastre_wizard.py, asistente_ladm_col/ui/wiz_create_responsibility_cadastre.ui, asistente_ladm_col/ui/wiz_create_restriction_cadastre.ui, asistente_ladm_col/ui/wiz_create_right_cadastre.ui
=> Make admin source selectable in wizard when creating RRR

asistente_ladm_col/gui/associate_extaddress_cadastre_wizard.py, asistente_ladm_col/ui/wiz_associate_extaddress_cadastre.ui
=> keep the previous selection in create extaddress wizard

asistente_ladm_col/asistente_ladm_col_plugin.py, asistente_ladm_col/config/general_config.py, asistente_ladm_col/config/help_strings.py, asistente_ladm_col/config/table_mapping_config.py, asistente_ladm_col/gui/associate_extaddress_cadastre_wizard.py, asistente_ladm_col/gui/create_parcel_cadastre_wizard.py, asistente_ladm_col/resources/toml/hide_fields_LADM.toml, asistente_ladm_col/tests/test_get_layers.py, asistente_ladm_col/ui/wiz_create_parcel_cadastre.ui, asistente_ladm_col/utils/logic_checks.py, asistente_ladm_col/utils/qgis_utils.py
=> Check constraint create parcel

asistente_ladm_col/asistente_ladm_col_plugin.py, asistente_ladm_col/utils/qgis_utils.py
=> [gui/core] alert when download dependency is process

asistente_ladm_col/gui/dlg_get_db_or_schema_name.py
=> [gui] Cursor is changed while the database or schema is being created

asistente_ladm_col/gui/qgis_model_baker/dlg_import_data.py, asistente_ladm_col/gui/qgis_model_baker/dlg_import_schema.py, asistente_ladm_col/gui/settings_dialog.py, asistente_ladm_col/ui/settings_dialog.ui
=> Add CRS Setting

asistente_ladm_col/gui/dlg_get_java_path.py, asistente_ladm_col/gui/reports.py, asistente_ladm_col/utils/utils.py
In reports:
1.Validate JAVA_HOME variable
2.If JAVA_HOME environment variable not exist we use java_home variable configured in QgisModelBaker
3.If java_home is not configured in QgisModelBaker we show the input dialog for the user to enter it.
=> Reports java home

asistente_ladm_col/asistente_ladm_col_plugin.py, asistente_ladm_col/gui/db_panel/db_config_panel.py, asistente_ladm_col/gui/db_panel/db_schema_db_panel.py, asistente_ladm_col/gui/db_panel/gpkg_config_panel.py, asistente_ladm_col/gui/db_panel/pg_config_panel.py, asistente_ladm_col/gui/official_data_settings_dialog.py, asistente_ladm_col/gui/settings_dialog.py, asistente_ladm_col/lib/db/db_connector.py, asistente_ladm_col/lib/db/db_factory.py, asistente_ladm_col/lib/db/gpkg_factory.py, asistente_ladm_col/lib/db/pg_factory.py
Fix bug associate with open setting dialog. 
(The heritage of dialogue settings was changed)
Thank you @yesidpol @gacarrillor
=> Fix bug setting dialog

asistente_ladm_col/gui/qgis_model_baker/dlg_import_data.py, asistente_ladm_col/lib/db/db_connection_manager.py, asistente_ladm_col/lib/db/pg_connector.py
=> Some adjustments

asistente_ladm_col/gui/dockwidget_queries.py
=> [gui] disconnect signal when dockwidget close

asistente_ladm_col/gui/change_detection/changes_per_parcel_panel.py, asistente_ladm_col/gui/change_detection/dockwidget_change_detection.py, asistente_ladm_col/ui/change_detection/changes_per_parcel_panel_widget.ui
=> Add spatial query in change detection.

asistente_ladm_col/data/ladm_data.py, asistente_ladm_col/gui/change_detection/changes_per_parcel_panel.py, asistente_ladm_col/gui/change_detection/dockwidget_change_detection.py
=> Show message when parcel doesn't have associated plot

asistente_ladm_col/data/qtmodels.py, asistente_ladm_col/gui/dockwidget_queries.py, asistente_ladm_col/utils/select_map_tool.py
Change import 'from PyQt5.' by 'from qgis.PyQt.'
=> Use the same version of pyqt as QGIS

asistente_ladm_col/asistente_ladm_col_plugin.py, asistente_ladm_col/gui/log_quality_dialog.py
Solution when change the name of database or schema and generate pdf of quality check results
=> Corrections when change the name of database and schema

asistente_ladm_col/asistente_ladm_col_plugin.py, asistente_ladm_col/gui/change_detection/changes_all_parcels_panel.py, asistente_ladm_col/gui/change_detection/changes_per_parcel_panel.py, asistente_ladm_col/gui/change_detection/dockwidget_change_detection.py, asistente_ladm_col/gui/change_detection/parcels_changes_summary_panel.py, asistente_ladm_col/i18n/Asistente-LADM_COL.pro
=> [changes] Make a proper distinction between 'all parcels' and 'per parcel'

asistente_ladm_col/gui/wizards/cadastre/party/dlg_create_group_party_cadastre.py
Validate fractions in group parties
=> Validate fractions in group parties

asistente_ladm_col/gui/wizards/abs_wizard_factory.py, asistente_ladm_col/gui/wizards/cadastre/spatial_unit/wiz_create_building_cadastre.py, asistente_ladm_col/gui/wizards/cadastre/spatial_unit/wiz_create_building_unit_cadastre.py, asistente_ladm_col/gui/wizards/cadastre/spatial_unit/wiz_create_plot_cadastre.py, asistente_ladm_col/gui/wizards/cadastre/spatial_unit/wiz_create_right_of_way_cadastre.py, asistente_ladm_col/gui/wizards/cadastre/surveying/wiz_create_points_cadastre.py, asistente_ladm_col/gui/wizards/spatial_wizard_factory.py, asistente_ladm_col/gui/wizards/valuation/wiz_create_geoeconomic_zone_valuation.py, asistente_ladm_col/gui/wizards/valuation/wiz_create_physical_zone_valuation.py, asistente_ladm_col/gui/wizards/wizard_factory.py
=> Tunning wizards

asistente_ladm_col/gui/dialogs/dlg_controlled_measurement.py, asistente_ladm_col/gui/dialogs/dlg_settings.py, asistente_ladm_col/gui/qgis_model_baker/dlg_import_data.py, asistente_ladm_col/gui/qgis_model_baker/dlg_import_schema.py, asistente_ladm_col/gui/right_of_way.py, asistente_ladm_col/gui/wizards/cadastre/spatial_unit/wiz_create_right_of_way_cadastre.py, asistente_ladm_col/tests/test_quality_validations.py, asistente_ladm_col/ui/dialogs/dlg_settings.ui, asistente_ladm_col/ui/qgis_model_baker/dlg_import_schema.ui, asistente_ladm_col/utils/geometry.py, asistente_ladm_col/utils/logic_checks.py, asistente_ladm_col/utils/quality.py
=> Use data source crs

asistente_ladm_col/config/general_config.py, asistente_ladm_col/gui/dialogs/dlg_settings.py, asistente_ladm_col/ui/dialogs/dlg_settings.ui, asistente_ladm_col/utils/qgis_utils.py
You can set the URL of the Transition System service in the settings dialog.
=> Add URL of the Transition System service in settings dialog.

asistente_ladm_col/gui/toolbar.py
Add cancel button in qmessagebox for:
=> add cancel button in qmessagebox for some actions

asistente_ladm_col/config/layer_config.py, asistente_ladm_col/config/refactor_fields_mappings.py, asistente_ladm_col/gui/wizards/operation/dlg_create_group_party_operation.py
=> Update automatic values in party and menor adjustments in group party

asistente_ladm_col/i18n/Asistente-LADM_COL.pro
Translatable files were included and those that are no longer translatable were removed
=> Update pro file.

asistente_ladm_col/asistente_ladm_col_plugin.py, asistente_ladm_col/lib/db/db_connection_manager.py, asistente_ladm_col/utils/decorators.py
=> Update db decorator qsettings changed

asistente_ladm_col/gui/dialogs/dlg_settings.py, asistente_ladm_col/gui/qgis_model_baker/dlg_export_data.py, asistente_ladm_col/gui/qgis_model_baker/dlg_import_data.py, asistente_ladm_col/gui/qgis_model_baker/dlg_import_schema.py, asistente_ladm_col/ui/dialogs/dlg_settings.ui
=> Alert to user if data validation at import/export is disabled

asistente_ladm_col/core/supplies/etl_snc.py, asistente_ladm_col/ui/supplies/wiz_supplies_etl.ui
Corrections for loading CSV on ETL_SNC
=> Fix load csv files

asistente_ladm_col/asistente_ladm_col_plugin.py, asistente_ladm_col/config/translation_strings.py, asistente_ladm_col/gui/change_detection/dlg_change_detection_settings.py, asistente_ladm_col/gui/dialogs/dlg_settings.py, asistente_ladm_col/gui/qgis_model_baker/dlg_export_data.py, asistente_ladm_col/gui/qgis_model_baker/dlg_import_data.py, asistente_ladm_col/gui/qgis_model_baker/dlg_import_schema.py, asistente_ladm_col/gui/supplies/wiz_supplies_etl.py, asistente_ladm_col/lib/context.py, asistente_ladm_col/lib/db/gpkg_connector.py, asistente_ladm_col/utils/decorators.py
And show message box explaining what will happen.
Also:
+ [x] Introduce SettingsContext to customize SettingsDialogs.
+ [x] Fix decorators (X_model_required)
=> [ux] Allow to save settings even if DB connection is invalid

asistente_ladm_col/config/gui/db_engine_gui_config.py, asistente_ladm_col/config/quality_rules_config.py, asistente_ladm_col/config/translation_strings.py, asistente_ladm_col/lib/db/mssql_factory.py, asistente_ladm_col/logic/ladm_col/mssql_ladm_query.py, asistente_ladm_col/logic/quality/logic_quality_rules.py, asistente_ladm_col/logic/quality/quality_rule_engine.py, asistente_ladm_col/logic/quality/quality_rule_layer_manager.py
Still pending (0/11):
+ [x] E4003
+ [x] E4008
+ [x] E4009
+ [x] E4010
+ [x] E4011
=> Support for MSSQL logic rules

asistente_ladm_col/lib/db/pg_connector.py, asistente_ladm_col/resources/toml/hide_fields_LADM.toml, asistente_ladm_col/tests/resources/xtf/empty_element_tag.xtf, asistente_ladm_col/tests/test_copy_csv_points_to_db.py, asistente_ladm_col/tests/utils.py
Minor adjustments migration to LADM 3
=> minor adjustments migration to LADM 3

asistente_ladm_col/asistente_ladm_col_plugin.py, asistente_ladm_col/config/gui/common_keys.py, asistente_ladm_col/config/ladm_names.py, asistente_ladm_col/config/task_steps_config.py, asistente_ladm_col/core/model_parser.py, asistente_ladm_col/gui/change_detection/dlg_change_detection_settings.py, asistente_ladm_col/gui/dialogs/dlg_load_layers.py, asistente_ladm_col/gui/gui_builder/gui_builder.py, asistente_ladm_col/gui/qgis_model_baker/dlg_export_data.py, asistente_ladm_col/gui/qgis_model_baker/dlg_import_data.py, asistente_ladm_col/gui/qgis_model_baker/dlg_import_schema.py, asistente_ladm_col/lib/db/db_connector.py, asistente_ladm_col/lib/ladm_col_models.py, asistente_ladm_col/tests/gui_tests/gui_tests_model_baker.py, asistente_ladm_col/tests/test_db_test_connection.py, asistente_ladm_col/tests/test_get_models.py, asistente_ladm_col/tests/test_interlis_utils.py, asistente_ladm_col/tests/test_qgis_model_baker.py, asistente_ladm_col/utils/decorators.py
=> Add LADM-COL model registry to manage data related to models

asistente_ladm_col/config/layer_config.py
=> Update display expressions

asistente_ladm_col/core/app_core_interface.py, asistente_ladm_col/core/supplies/etl_cobol.py, asistente_ladm_col/gui/supplies/dlg_cobol_base.py
=> Normalizate URIs

asistente_ladm_col/lib/db/mssql_connector.py, asistente_ladm_col/ui/dialogs/settings_mssql.ui
=> Mssql minor issues

Dockerfile
'latest' has been failing for weeks...
=> [ci] Point to release 3.14 for unit tests 

asistente_ladm_col/config/general_config.py, asistente_ladm_col/gui/dialogs/dlg_settings.py, asistente_ladm_col/lib/source_handler.py
And set the default value to False (disabled).
=> [settings] Avoid enabling an invalid source service 

asistente_ladm_col/gui/reports/reports.py, asistente_ladm_col/logic/ladm_col/config/reports/annex_17_report/pg/annex17_point_data_query.py
Handle error associated with processBar removed
=> [fix] handle error associated with processBar removed

asistente_ladm_col/lib/geometry.py
As it may produce invalid geometries (Fix #381)
=> [geometry] Make sure we fix geoemtries after add_topological_points

asistente_ladm_col/core/app_core_interface.py, asistente_ladm_col/lib/geometry.py, asistente_ladm_col/lib/processing/algs/CopyVectorLayer.py, asistente_ladm_col/lib/processing/ladm_col_provider.py, asistente_ladm_col/logic/quality/polygon_quality_rules.py, asistente_ladm_col/logic/quality/quality_rule_layer_manager.py, asistente_ladm_col/tests/test_quality_validations.py
We make sure to add topological vertices from building to plot, before checking spatial relations. 
+ [x] QR 3009 (building --> plot)
+ [x] QR 3010 (building unit --> plot)
+ [x] QR 3011 (building unit --> building)
Fix #410
=> Fix QR buildings whould be within plot

asistente_ladm_col/lib/geometry.py, asistente_ladm_col/logic/quality/line_quality_rules.py, asistente_ladm_col/logic/quality/point_quality_rules.py, asistente_ladm_col/logic/quality/polygon_quality_rules.py
=> [quality] Create intermediate spatial indexes

asistente_ladm_col/core/app_core_interface.py, asistente_ladm_col/lib/geometry.py, asistente_ladm_col/lib/processing/algs/CopyVectorLayer.py, asistente_ladm_col/lib/processing/models/model_overlapping_boundaries.model3, asistente_ladm_col/logic/quality/line_quality_rules.py
For the quality rule: 'Boundaries should not overlap'.
Fix #438
=> [quality] Add support for line self-intersections (of type point)

asistente_ladm_col/core/app_core_interface.py, asistente_ladm_col/lib/geometry.py, asistente_ladm_col/logic/quality/line_quality_rules.py, asistente_ladm_col/logic/quality/point_quality_rules.py, asistente_ladm_col/logic/quality/polygon_quality_rules.py, asistente_ladm_col/logic/quality/quality_rule_layer_manager.py
From commits bc6891a and ed1fa99
=> [quality] Add spatial index to improve performance of quality rules

asistente_ladm_col/lib/quality_rule/quality_rule_manager.py, asistente_ladm_col/logic/quality/quality_rule_engine.py, asistente_ladm_col/tests/test_quality_rules.py
Also, add unit test for rule_key not found
=> [quality] Accept dict or list to pass quality rule keys to QREngine

asistente_ladm_col/asistente_ladm_col_plugin.py, asistente_ladm_col/gui/app_gui_interface.py, asistente_ladm_col/gui/queries/dockwidget_queries.py, asistente_ladm_col/gui/queries/ladm_query_controller.py, asistente_ladm_col/logic/ladm_col/tree_models.py
To separate queries' logic from GUI.
=> [queries] Add LADM query controller

asistente_ladm_col/gui/field_data_capture/allocation/fdc_data_exporter.py, asistente_ladm_col/gui/field_data_capture/base_fdc_allocation_controller.py, asistente_ladm_col/lib/db/db_connector.py, asistente_ladm_col/lib/db/gpkg_connector.py, asistente_ladm_col/utils/utils.py
Which for some reason was generating incomplete offline data for surveyors (due to missing data in the intermediate XTF itself).
Ready to test.
=> [field-data] Fix allocation from GPKG

.docker/docker-compose.yml, asistente_ladm_col/gui/qgis_model_baker/dlg_import_schema.py
Updates the expression to select the models to be used in create structure dialog when it is called from import data dialog
=> [fix] Update selected models in create structure when it is called from import data dialog 

asistente_ladm_col/core/reports/base_report_generator.py, asistente_ladm_col/gui/reports/ant_report_dialog.py
=> Map services available to generate the ANT report are validated

asistente_ladm_col/config/translation_strings.py, asistente_ladm_col/logic/ladm_col/gpkg_ladm_query.py, asistente_ladm_col/logic/ladm_col/mssql_ladm_query.py, asistente_ladm_col/logic/ladm_col/pg_ladm_query.py
=> [quality] QR E4010 does no longer check a Building Unit association for 'NPH'

asistente_ladm_col/config/quality_rules_config.py, asistente_ladm_col/core/app_core_interface.py, asistente_ladm_col/lib/geometry.py, asistente_ladm_col/logic/quality/polygon_quality_rules.py, asistente_ladm_col/tests/test_quality_validations.py
=> [geometry] Add_topological_vertices now always returns a fixed layer

asistente_ladm_col/utils/interlis_utils.py
https://github.com/jbarlow83/OCRmyPDF/issues/583
=> Python 3.9 error with etree library:

asistente_ladm_col/logic/ladm_col/gpkg_ladm_query.py, asistente_ladm_col/logic/ladm_col/mssql_ladm_query.py, asistente_ladm_col/logic/ladm_col/pg_ladm_query.py
=> [quality] Parcels that are of public use SHOULD have a plot associated and COULD have buildings and building units associated

asistente_ladm_col/lib/qgis_model_baker/ili2db.py, asistente_ladm_col/utils/decorators.py
We'll need it soon to deal with Field Data Capture and other auxiliary models.
Source: Field Data Capture branch.
https://github.com/SwissTierrasColombia/Asistente-LADM-COL/commits/qfield_integration_basket_basket/asistente_ladm_col/lib/qgis_model_baker/ili2db.py
=> [lib] Introduce Ili2Db class to execute ili2db commands (via Model Baker API)

asistente_ladm_col/core/reports/base_report_generator.py, asistente_ladm_col/lib/geometry.py
=> [fix] Use constGet instead of get to prevent unexpected errors

asistente_ladm_col/logic/ladm_col/gpkg_ladm_query.py, asistente_ladm_col/logic/ladm_col/pg_ladm_query.py
...since it is a float point number.
Ref #521
=> [quality] Fix sum of fractions by rounding the result

asistente_ladm_col/config/general_config.py, asistente_ladm_col/core/reports/annex_17_report_generator.py, asistente_ladm_col/core/reports/ant_report_generator.py, asistente_ladm_col/core/reports/base_report_generator.py
- Temporary files used to create the report are removed
- Report file name is customized
fix #525
=> [reports] Update ANT report version from 1.1.0 to 1.2.0

asistente_ladm_col/core/ili2db.py, asistente_ladm_col/gui/qgis_model_baker/dlg_export_data.py, asistente_ladm_col/gui/qgis_model_baker/dlg_import_data.py, asistente_ladm_col/gui/qgis_model_baker/dlg_import_schema.py, asistente_ladm_col/utils/quality_error_db_utils.py
=> Change "data management" dialogs to use ili2db class

README.md, README_en.md
PR to see if things work well embedding a video into the READMEs
=> Update READMEs with QR new generation video

asistente_ladm_col/resources/toml/LADM_COL_configuration.toml
Reorder toml file for better reading.
Create and Update new attributes
=> [Config] Update LADM_COL_configuration.toml to 1.2 Survey model
